import { PrismaClient, Platform } from '@prisma/client'

const prisma = new PrismaClient()

const ideas = [
  {
    slug: "idle-fossil-hunter",
    title: "Idle Fossil Hunter",
    genre: "Idle / Clicker",
    platform: Platform.mobile,
    hook: "Dig through geological layers while you sleep — wake up to prehistoric treasures",
    problem: "Idle games lack educational value; fossil/archaeology themes underexplored in casual mobile",
    opportunity: "Idle games hit $2.3B in 2025. Paleontology content trending (Jurassic World franchise, museum visits up 40%)",
    marketSize: "$2.3B idle game market, 15% YoY growth",
    targetAudience: "Casual mobile gamers 25-45, science enthusiasts, museum lovers",
    competitionAnalysis: "No dominant fossil-themed idle game. Closest: Idle Miner Tycoon (mining, not fossils), Egg Inc (farming). Gap: educational + collectible focus",
    similarGames: JSON.stringify([
      { name: "Idle Miner Tycoon", revenue: "$150M lifetime", downloads: "100M+", notes: "Mining theme, no education" },
      { name: "Egg Inc", revenue: "$50M+", downloads: "50M+", notes: "Idle mechanics, quirky theme" },
      { name: "Cell to Singularity", revenue: "$20M+", downloads: "10M+", notes: "Educational idle, evolution theme" }
    ]),
    whyNow: "Post-pandemic museum boom, idle genre mature but theme-starved, AI can generate unique fossil art cheaply",
    buildEstimateHours: 120,
    techStack: "Unity + PlayFab (backend) + AdMob",
    monetization: "Ads (rewarded video for dig speed) + IAP ($2.99-$9.99 gem packs) + Battle Pass ($4.99/month)",
    distributionPlan: "Soft launch in Canada/Australia, TikTok influencer seeding, r/incremental_games community",
    scoreMarket: 22,
    scoreDifficulty: 20,
    scoreCompetition: 23,
    scoreMonetization: 13,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
    featuredDate: new Date(),
  },
  {
    slug: "reverse-tower-defense",
    title: "Creep Commander",
    genre: "Reverse Tower Defense",
    platform: Platform.both,
    hook: "You ARE the creeps — build the perfect wave to overwhelm human defenses",
    problem: "Tower defense is stale; always defending. Reverse TD exists but poorly executed on mobile",
    opportunity: "TD genre $800M annually. Reverse TD viral on Steam (Anomaly series) but no mobile hit",
    marketSize: "$800M tower defense market",
    targetAudience: "Strategy gamers 18-35, TD veterans looking for fresh take",
    competitionAnalysis: "Anomaly series (PC, old). No modern mobile reverse TD with polish. Gap: mobile-first, roguelike elements",
    similarGames: JSON.stringify([
      { name: "Anomaly Warzone Earth", revenue: "$5M+", downloads: "2M+", notes: "PC reverse TD, dated" },
      { name: "Kingdom Rush", revenue: "$30M+", downloads: "50M+", notes: "Classic TD, premium" },
      { name: "Bloons TD 6", revenue: "$100M+", downloads: "30M+", notes: "Top TD, not reverse" }
    ]),
    whyNow: "Roguelike mechanics trending, mobile strategy audience grown 40%, AI for level generation",
    buildEstimateHours: 200,
    techStack: "Godot 4 + SQLite (local saves) + GameAnalytics",
    monetization: "Premium $4.99 + IAP cosmetics + Season Pass",
    distributionPlan: "Steam demo first, cross-promo with TD YouTubers, Reddit r/towerdefense",
    scoreMarket: 18,
    scoreDifficulty: 16,
    scoreCompetition: 24,
    scoreMonetization: 12,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "one-button-roguelike",
    title: "Tap Survivor",
    genre: "Roguelike / Casual",
    platform: Platform.mobile,
    hook: "Vampire Survivors meets one-tap controls — the most accessible roguelike ever",
    problem: "Vampire Survivors clones require too much input for casual mobile play",
    opportunity: "VS-likes exploded ($100M+ genre) but mobile versions feel cramped. One-button = perfect fit",
    marketSize: "Vampire Survivors-like genre: $100M+ in 2024-25",
    targetAudience: "Casual mobile gamers, VS fans who want simpler mobile experience",
    competitionAnalysis: "Survivor.io ($200M) proved mobile demand but complex controls. Gap: radical simplification",
    similarGames: JSON.stringify([
      { name: "Survivor.io", revenue: "$200M+", downloads: "80M+", notes: "Mobile VS clone, joystick controls" },
      { name: "Vampire Survivors", revenue: "$50M+", downloads: "10M+", notes: "PC original, minimal controls" },
      { name: "Brotato", revenue: "$15M+", downloads: "5M+", notes: "Top-down roguelike, controller focus" }
    ]),
    whyNow: "VS fatigue setting in — need innovation. One-hand play = commuter perfect",
    buildEstimateHours: 80,
    techStack: "Unity + Unity Gaming Services + ironSource",
    monetization: "Ads (interstitial between runs) + IAP characters ($1.99 each) + Remove Ads $3.99",
    distributionPlan: "TikTok gameplay clips, cross-promo with hyper-casual publishers, r/roguelikes",
    scoreMarket: 23,
    scoreDifficulty: 22,
    scoreCompetition: 20,
    scoreMonetization: 14,
    scoreTiming: 7,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "ai-dungeon-master",
    title: "Pocket DM",
    genre: "AI RPG / Text Adventure",
    platform: Platform.mobile,
    hook: "GPT-powered dungeon master in your pocket — infinite campaigns, zero prep",
    problem: "D&D requires coordination, prep, scheduling. Solo D&D tools are dice-rollers, not storytellers",
    opportunity: "D&D hit $1B+ in 2024. AI Dungeon proved demand (10M+ users) but quality inconsistent",
    marketSize: "D&D/TTRPG market: $1B+, AI gaming tools: $500M+",
    targetAudience: "D&D players without groups, fantasy fans, commuters wanting narrative",
    competitionAnalysis: "AI Dungeon (broad, unfocused). No D&D-specific AI DM with proper rules engine",
    similarGames: JSON.stringify([
      { name: "AI Dungeon", revenue: "$20M+", downloads: "10M+", notes: "Open-ended, no structure" },
      { name: "Baldur's Gate 3", revenue: "$500M+", downloads: "15M+", notes: "Premium CRPG, not mobile" },
      { name: "D&D Beyond", revenue: "$100M+", downloads: "5M+", notes: "Companion app, not game" }
    ]),
    whyNow: "GPT-4 quality leap, D&D movie success, BG3 GOTY brought millions of new fans",
    buildEstimateHours: 160,
    techStack: "React Native + OpenAI GPT-4o-mini + Supabase",
    monetization: "Freemium (3 sessions free) + $9.99/mo subscription + Lifetime $79.99",
    distributionPlan: "D&D subreddits, Critical Role community, TTRPG podcasts",
    scoreMarket: 21,
    scoreDifficulty: 15,
    scoreCompetition: 22,
    scoreMonetization: 14,
    scoreTiming: 10,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "cozy-delivery-sim",
    title: "Village Courier",
    genre: "Cozy Simulation",
    platform: Platform.both,
    hook: "Run a delivery service in a Studio Ghibli-inspired village — no combat, just vibes",
    problem: "Cozy games booming but delivery genre (Death Stranding) is hardcore. Gap: cozy delivery",
    opportunity: "Cozy games $2B+ market. Delivery mechanics proven addictive. Combination unexplored",
    marketSize: "Cozy game market: $2B+, 25% YoY growth",
    targetAudience: "Cozy gamers 20-40, Stardew Valley fans, anti-stress seekers",
    competitionAnalysis: "Stardew (farming), Animal Crossing (life sim), Death Stranding (hardcore delivery). No cozy delivery sim",
    similarGames: JSON.stringify([
      { name: "Stardew Valley", revenue: "$300M+", downloads: "30M+", notes: "Cozy farming, no delivery focus" },
      { name: "Unpacking", revenue: "$30M+", downloads: "3M+", notes: "Cozy puzzle, narrative" },
      { name: "A Short Hike", revenue: "$5M+", downloads: "1M+", notes: "Cozy exploration, short" }
    ]),
    whyNow: "Post-pandemic cozy boom, Ghibli film releases driving aesthetic interest",
    buildEstimateHours: 180,
    techStack: "Godot 4 + Aseprite (pixel art) + Steam Workshop",
    monetization: "Premium $14.99 + DLC villages ($4.99 each)",
    distributionPlan: "Steam Next Fest demo, cozy game subreddits, Wholesome Direct",
    scoreMarket: 20,
    scoreDifficulty: 17,
    scoreCompetition: 23,
    scoreMonetization: 11,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "micro-city-builder",
    title: "Tiny Towns",
    genre: "Puzzle / City Builder",
    platform: Platform.mobile,
    hook: "Build a city in 5 minutes — bite-sized city planning for your commute",
    problem: "City builders require hours. Mobile versions (SimCity BuildIt) are pay-to-win grinders",
    opportunity: "Puzzle + city builder hybrid untapped. Mini Motorways proved micro-strategy works",
    marketSize: "City builder: $1B+, Puzzle games: $8B+",
    targetAudience: "Puzzle gamers, lapsed city builder fans, commuters",
    competitionAnalysis: "Mini Motorways (traffic puzzle), SimCity BuildIt (F2P grind). Gap: quick session city builder with puzzle depth",
    similarGames: JSON.stringify([
      { name: "Mini Motorways", revenue: "$20M+", downloads: "5M+", notes: "Traffic puzzle, elegant" },
      { name: "SimCity BuildIt", revenue: "$500M+", downloads: "100M+", notes: "F2P grind, timers" },
      { name: "Islanders", revenue: "$5M+", downloads: "2M+", notes: "Minimalist builder, PC" }
    ]),
    whyNow: "Mini Motorways success, puzzle fatigue = need fresh mechanics, mobile city builder market underserved",
    buildEstimateHours: 100,
    techStack: "Unity + Unity Ads + Firebase",
    monetization: "Premium $3.99 + hint IAP ($0.99-$4.99) + Daily Challenge pass $1.99/mo",
    distributionPlan: "Apple Arcade pitch, r/iosgaming, city builder YouTubers",
    scoreMarket: 21,
    scoreDifficulty: 21,
    scoreCompetition: 22,
    scoreMonetization: 12,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "rhythm-roguelike",
    title: "Beat Dungeon",
    genre: "Rhythm / Roguelike",
    platform: Platform.both,
    hook: "Crypt of the NecroDancer meets Hades — move to the music, die to the beat",
    problem: "Rhythm roguelikes exist but are niche. Opportunity to mainstream with polish + accessibility",
    opportunity: "Rhythm games $3B+. Roguelikes $500M+. Hybrid = underexplored premium segment",
    marketSize: "Rhythm games: $3B+, Roguelikes: $500M+",
    targetAudience: "Rhythm game fans, roguelike addicts, Spotify generation gamers",
    competitionAnalysis: "Crypt of NecroDancer (cult hit, dated). BPM: Bullets Per Minute (FPS rhythm). Gap: accessible 2D action",
    similarGames: JSON.stringify([
      { name: "Crypt of the NecroDancer", revenue: "$20M+", downloads: "5M+", notes: "Pioneer, grid-based" },
      { name: "Hades", revenue: "$300M+", downloads: "10M+", notes: "Top roguelike, no rhythm" },
      { name: "Beat Saber", revenue: "$250M+", downloads: "6M+", notes: "VR rhythm, not roguelike" }
    ]),
    whyNow: "Hades 2 hype, lo-fi beats culture, procedural music AI makes soundtrack generation viable",
    buildEstimateHours: 200,
    techStack: "Unity + FMOD (audio) + Steamworks",
    monetization: "Premium $19.99 + Soundtrack DLC $4.99 + Music pack expansions",
    distributionPlan: "Steam Next Fest, rhythm game YouTubers, Spotify playlist placement",
    scoreMarket: 19,
    scoreDifficulty: 14,
    scoreCompetition: 21,
    scoreMonetization: 12,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "pet-battle-autobattler",
    title: "Critter Clash",
    genre: "Auto Battler / Pet Collection",
    platform: Platform.mobile,
    hook: "Pokemon meets Teamfight Tactics — collect, position, win automatically",
    problem: "Auto battlers (TFT, Hearthstone BG) are complex. Pet collection games lack depth. Combine = casual depth",
    opportunity: "Auto battler $1B+ segment. Pet collection evergreen. Mobile-first opportunity",
    marketSize: "Auto battlers: $1B+, Pet collection: $2B+",
    targetAudience: "TFT players wanting mobile-first, Pokemon fans wanting strategy, casual collectors",
    competitionAnalysis: "TFT Mobile (complex), Pokemon Unite (MOBA not autobattler). Gap: cute + casual + strategic",
    similarGames: JSON.stringify([
      { name: "Teamfight Tactics", revenue: "$200M+", downloads: "50M+", notes: "Complex, PC-first" },
      { name: "Pokemon Unite", revenue: "$100M+", downloads: "80M+", notes: "MOBA, not autobattler" },
      { name: "Axie Infinity", revenue: "$1B+ (peak)", downloads: "10M+", notes: "Crypto, crashed" }
    ]),
    whyNow: "Axie collapse left void, TFT mobile disappoints, Palworld proved pet collection hunger",
    buildEstimateHours: 160,
    techStack: "Unity + PlayFab + AppLovin MAX",
    monetization: "F2P gacha (critter pulls) + Battle Pass $9.99/season + Cosmetics",
    distributionPlan: "TikTok critter reveals, auto battler streamers, r/autochess",
    scoreMarket: 22,
    scoreDifficulty: 15,
    scoreCompetition: 20,
    scoreMonetization: 14,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "narrative-puzzle-box",
    title: "The Unopened",
    genre: "Puzzle / Horror",
    platform: Platform.both,
    hook: "Solve intricate puzzle boxes that reveal disturbing stories — The Room meets Doki Doki",
    problem: "The Room series ended. Puzzle box genre stagnant. Horror puzzles = untapped crossover",
    opportunity: "Puzzle genre $8B. Horror indie boom. Combination (horror puzzle) rare",
    marketSize: "Puzzle: $8B, Horror games: $2B+",
    targetAudience: "The Room fans, horror enthusiasts, puzzle completionists",
    competitionAnalysis: "The Room series (done), Resident Evil puzzles (embedded in action). Gap: standalone horror puzzle",
    similarGames: JSON.stringify([
      { name: "The Room", revenue: "$50M+", downloads: "20M+", notes: "Puzzle box pioneer, series ended" },
      { name: "FNAF", revenue: "$100M+", downloads: "50M+", notes: "Horror, not puzzle focus" },
      { name: "Inscryption", revenue: "$30M+", downloads: "2M+", notes: "Horror card game, PC" }
    ]),
    whyNow: "The Room void, analog horror trending, escape room popularity peak",
    buildEstimateHours: 140,
    techStack: "Unity + Wwise (audio) + haptic feedback SDK",
    monetization: "Premium $6.99 + Chapter DLC $2.99 each",
    distributionPlan: "Horror YouTubers (Markiplier etc), r/horror, The Room community",
    scoreMarket: 20,
    scoreDifficulty: 18,
    scoreCompetition: 24,
    scoreMonetization: 11,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "sports-management-idle",
    title: "Idle FC",
    genre: "Idle / Sports Management",
    platform: Platform.mobile,
    hook: "Football Manager meets idle games — build your dynasty while AFK",
    problem: "Sports management games require hours. Idle games lack sports theme. Combine = mass market",
    opportunity: "Sports games $15B+. Idle $2B+. Idle sports management = white space",
    marketSize: "Sports games: $15B+, Idle: $2B+",
    targetAudience: "Football fans, FM players without time, idle game addicts wanting theme",
    competitionAnalysis: "Football Manager (hardcore), Top Eleven (complex F2P). No idle-first sports management",
    similarGames: JSON.stringify([
      { name: "Football Manager", revenue: "$100M+", downloads: "10M+", notes: "Hardcore, time-intensive" },
      { name: "Top Eleven", revenue: "$300M+", downloads: "100M+", notes: "F2P, still complex" },
      { name: "Idle Miner Tycoon", revenue: "$150M+", downloads: "100M+", notes: "Idle pioneer, not sports" }
    ]),
    whyNow: "World Cup cycle, FM mobile disappoints casual fans, idle genre needs fresh themes",
    buildEstimateHours: 120,
    techStack: "Unity + Firebase + AdMob",
    monetization: "Ads (rewarded for scout reports) + IAP gems + VIP subscription $4.99/mo",
    distributionPlan: "Football Twitter/X, r/footballmanagergames, sports podcasts",
    scoreMarket: 23,
    scoreDifficulty: 19,
    scoreCompetition: 24,
    scoreMonetization: 14,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "word-battle-royale",
    title: "Last Word Standing",
    genre: "Word Game / Battle Royale",
    platform: Platform.mobile,
    hook: "99 players, one word puzzle — fastest fingers win. Wordle meets Fall Guys",
    problem: "Word games (Wordle) are solo. Multiplayer word games (Words with Friends) are slow async",
    opportunity: "Word games $3B+. Real-time multiplayer trending. Combination = viral potential",
    marketSize: "Word/puzzle: $3B+, Battle royale: $5B+",
    targetAudience: "Wordle addicts, competitive puzzlers, party game fans",
    competitionAnalysis: "Wordle (solo daily), Words with Friends (async 1v1). No real-time mass multiplayer word game",
    similarGames: JSON.stringify([
      { name: "Wordle", revenue: "NYT acquisition", downloads: "300M+ web plays", notes: "Solo, daily limit" },
      { name: "Words with Friends", revenue: "$100M+", downloads: "100M+", notes: "Async, slow" },
      { name: "Fall Guys", revenue: "$200M+", downloads: "50M+", notes: "Battle royale party, not word" }
    ]),
    whyNow: "Wordle created word game renaissance, real-time mobile infrastructure mature, short-form competition trending",
    buildEstimateHours: 140,
    techStack: "Unity + Photon (multiplayer) + PlayFab",
    monetization: "F2P cosmetics + Battle Pass $5.99/season + Ad-free $3.99",
    distributionPlan: "TikTok gameplay clips, Wordle communities, streaming potential",
    scoreMarket: 22,
    scoreDifficulty: 16,
    scoreCompetition: 25,
    scoreMonetization: 13,
    scoreTiming: 10,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "diy-escape-room-maker",
    title: "Escape Architect",
    genre: "Puzzle / Creator",
    platform: Platform.both,
    hook: "Create and share escape rooms — Roblox meets The Room",
    problem: "Escape room games are one-and-done. User-generated content = infinite replayability",
    opportunity: "UGC platforms $10B+. Escape room games popular but finite content",
    marketSize: "UGC gaming: $10B+, Puzzle: $8B+",
    targetAudience: "Escape room fans, creators, puzzle designers, streamers",
    competitionAnalysis: "The Room (finite), Escape Simulator (PC UGC). No mobile-first escape room creator",
    similarGames: JSON.stringify([
      { name: "Escape Simulator", revenue: "$20M+", downloads: "2M+", notes: "PC UGC, not mobile" },
      { name: "Roblox", revenue: "$2B+", downloads: "500M+", notes: "UGC platform, broad" },
      { name: "The Room", revenue: "$50M+", downloads: "20M+", notes: "Finite content" }
    ]),
    whyNow: "Creator economy boom, escape room genre needs refresh, mobile creation tools viable now",
    buildEstimateHours: 250,
    techStack: "Unity + cloud save (AWS) + mod.io",
    monetization: "F2P play + Creator subscription $9.99/mo + Featured placement IAP",
    distributionPlan: "Escape room YouTubers, level design communities, cross-promo with physical escape rooms",
    scoreMarket: 19,
    scoreDifficulty: 12,
    scoreCompetition: 23,
    scoreMonetization: 12,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "plant-care-rpg",
    title: "Sprout Quest",
    genre: "RPG / Simulation",
    platform: Platform.mobile,
    hook: "Your houseplants are heroes — care for them IRL to power them up in-game",
    problem: "Plant apps are utilities. Plant games are decorators. No plant game with real stakes",
    opportunity: "Plant parent culture huge. Tamagotchi nostalgia. IRL-game hybrid trending",
    marketSize: "Plant apps: $500M+, Virtual pet: $1B+",
    targetAudience: "Plant parents 25-40, Tamagotchi generation, cozy gamers",
    competitionAnalysis: "Planta (plant care utility), Viridi (plant decoration). No plant RPG with IRL connection",
    similarGames: JSON.stringify([
      { name: "Planta", revenue: "$30M+", downloads: "5M+", notes: "Utility, not game" },
      { name: "Viridi", revenue: "$1M+", downloads: "1M+", notes: "Decoration, passive" },
      { name: "Pikmin Bloom", revenue: "$50M+", downloads: "10M+", notes: "Walking game, not plants" }
    ]),
    whyNow: "Plant parent identity strong, wellness gaming trending, Pikmin Bloom proved IRL-game works",
    buildEstimateHours: 140,
    techStack: "React Native + OpenCV (plant recognition) + Supabase",
    monetization: "Premium $4.99 + Plant species IAP ($1.99-$3.99) + Rare seeds subscription $2.99/mo",
    distributionPlan: "Plant TikTok/Instagram, r/houseplants, plant shop partnerships",
    scoreMarket: 18,
    scoreDifficulty: 16,
    scoreCompetition: 24,
    scoreMonetization: 12,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "cooking-tower-defense",
    title: "Kitchen Siege",
    genre: "Tower Defense / Cooking",
    platform: Platform.mobile,
    hook: "Place dishes as towers to satisfy an endless horde of hungry customers",
    problem: "Cooking games = time management. TD = strategy. Combine for unique stress-fun loop",
    opportunity: "Cooking games $1B+. TD $800M. Hybrid = blue ocean",
    marketSize: "Cooking games: $1B+, Tower defense: $800M",
    targetAudience: "Cooking game fans, TD strategists, Overcooked lovers",
    competitionAnalysis: "Overcooked (co-op chaos), Kingdom Rush (pure TD). No cooking TD hybrid",
    similarGames: JSON.stringify([
      { name: "Overcooked", revenue: "$100M+", downloads: "10M+", notes: "Cooking co-op, not TD" },
      { name: "Kingdom Rush", revenue: "$30M+", downloads: "50M+", notes: "Fantasy TD" },
      { name: "Cooking Fever", revenue: "$200M+", downloads: "200M+", notes: "Time management, not TD" }
    ]),
    whyNow: "Cooking content still viral, TD needs innovation, mash-up games trending",
    buildEstimateHours: 130,
    techStack: "Unity + LevelPlay (ads) + Firebase",
    monetization: "F2P with ads + Recipe book IAP ($2.99-$9.99) + Chef skins",
    distributionPlan: "Food TikTok, casual game influencers, cooking subreddits",
    scoreMarket: 20,
    scoreDifficulty: 18,
    scoreCompetition: 24,
    scoreMonetization: 13,
    scoreTiming: 7,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "sleep-adventure",
    title: "Dreamwalker",
    genre: "Idle / Adventure",
    platform: Platform.mobile,
    hook: "Progress only while you sleep — your hero adventures through your dreams",
    problem: "Sleep apps are boring utilities. Games keep you awake. Combine = healthy engagement",
    opportunity: "Sleep apps $2B+. Idle games $2B+. Sleep-game hybrid = wellness gaming",
    marketSize: "Sleep/wellness apps: $2B+, Idle games: $2B+",
    targetAudience: "Sleep-conscious adults, idle gamers, wellness seekers",
    competitionAnalysis: "Headspace (meditation), Sleep Cycle (tracker), Pokemon Sleep (limited gameplay). Gap: actual game mechanics",
    similarGames: JSON.stringify([
      { name: "Pokemon Sleep", revenue: "$100M+", downloads: "20M+", notes: "Sleep tracker with Pokemon, minimal game" },
      { name: "Headspace", revenue: "$100M+", downloads: "70M+", notes: "Meditation, not game" },
      { name: "Idle Heroes", revenue: "$500M+", downloads: "50M+", notes: "Idle RPG, not sleep-linked" }
    ]),
    whyNow: "Pokemon Sleep proved sleep-gaming concept, wellness gaming maturing, sleep deprivation epidemic",
    buildEstimateHours: 120,
    techStack: "React Native + HealthKit/Google Fit + RevenueCat",
    monetization: "Freemium + Premium sleep insights $4.99/mo + Dream world expansions IAP",
    distributionPlan: "Sleep/wellness influencers, health app cross-promo, r/sleep",
    scoreMarket: 21,
    scoreDifficulty: 17,
    scoreCompetition: 22,
    scoreMonetization: 13,
    scoreTiming: 10,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "tycoon-true-crime",
    title: "Cold Case Tycoon",
    genre: "Tycoon / Mystery",
    platform: Platform.both,
    hook: "Run a true crime podcast empire — investigate cases, build audience, solve mysteries",
    problem: "True crime games = narrative adventures. Tycoon = business sim. Combine = genre-defining",
    opportunity: "True crime podcast market $1B+. Tycoon games $2B+. No true crime tycoon exists",
    marketSize: "True crime content: $1B+, Tycoon games: $2B+",
    targetAudience: "True crime podcast addicts, tycoon gamers, mystery lovers",
    competitionAnalysis: "Her Story (narrative), Game Dev Tycoon (tycoon). No true crime business sim",
    similarGames: JSON.stringify([
      { name: "Game Dev Tycoon", revenue: "$20M+", downloads: "5M+", notes: "Business sim, not true crime" },
      { name: "Her Story", revenue: "$10M+", downloads: "1M+", notes: "Mystery, not tycoon" },
      { name: "Papers Please", revenue: "$15M+", downloads: "3M+", notes: "Narrative sim, not tycoon" }
    ]),
    whyNow: "True crime at peak popularity, podcast culture mainstream, meta-games (game about games) trending",
    buildEstimateHours: 180,
    techStack: "Godot 4 + SQLite + Steamworks",
    monetization: "Premium $12.99 + Case pack DLC $3.99 each",
    distributionPlan: "True crime podcasts (sponsor/feature), Reddit r/truecrime, Steam mystery tag",
    scoreMarket: 20,
    scoreDifficulty: 16,
    scoreCompetition: 25,
    scoreMonetization: 11,
    scoreTiming: 9,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "music-merge",
    title: "Melody Merge",
    genre: "Merge / Music",
    platform: Platform.mobile,
    hook: "Merge instruments to compose symphonies — the chill merge game that creates music",
    problem: "Merge games are visual-only satisfaction. Music games require skill. Combine = accessible music creation",
    opportunity: "Merge games $3B+. Music games $3B+. Merge-music hybrid = untapped",
    marketSize: "Merge games: $3B+, Music games: $3B+",
    targetAudience: "Merge game addicts, music lovers without skill, ASMR seekers",
    competitionAnalysis: "Merge Mansion (narrative merge), Beat Saber (skill music). No merge-to-music game",
    similarGames: JSON.stringify([
      { name: "Merge Mansion", revenue: "$500M+", downloads: "50M+", notes: "Merge + narrative" },
      { name: "Incredibox", revenue: "$20M+", downloads: "10M+", notes: "Music creation, not merge" },
      { name: "Piano Tiles", revenue: "$100M+", downloads: "500M+", notes: "Rhythm, not merge" }
    ]),
    whyNow: "Merge genre saturated, needs innovation. Lo-fi music culture huge. ASMR/satisfying content at peak",
    buildEstimateHours: 100,
    techStack: "Unity + FMOD + AdMob",
    monetization: "F2P ads + Remove ads $3.99 + Instrument packs IAP $1.99-$4.99",
    distributionPlan: "ASMR/satisfying TikTok, lo-fi communities, merge game cross-promo",
    scoreMarket: 22,
    scoreDifficulty: 20,
    scoreCompetition: 23,
    scoreMonetization: 13,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "archaeology-survivor",
    title: "Dig or Die",
    genre: "Survival / Archaeology",
    platform: Platform.both,
    hook: "Survive ancient traps while excavating — Indiana Jones meets Don't Starve",
    problem: "Archaeology games are puzzles (Tomb Raider) or sims. Survival = new take",
    opportunity: "Survival games $5B+. Archaeology theme underused. Combo = fresh",
    marketSize: "Survival games: $5B+",
    targetAudience: "Survival game fans, Indiana Jones lovers, history buffs",
    competitionAnalysis: "Tomb Raider (action-adventure), Don't Starve (survival, no theme). Gap: archaeology survival",
    similarGames: JSON.stringify([
      { name: "Don't Starve", revenue: "$100M+", downloads: "15M+", notes: "Survival, wilderness theme" },
      { name: "Tomb Raider", revenue: "$1B+", downloads: "50M+", notes: "Action-adventure, AAA" },
      { name: "Subnautica", revenue: "$150M+", downloads: "10M+", notes: "Survival, underwater" }
    ]),
    whyNow: "New Indiana Jones movie, survival genre mature but theme-starved, roguelike survival trending",
    buildEstimateHours: 200,
    techStack: "Godot 4 + procedural generation + Steam Workshop",
    monetization: "Premium $14.99 + Expedition DLC $4.99",
    distributionPlan: "Survival game streamers, archaeology subreddits, Steam survival tag",
    scoreMarket: 19,
    scoreDifficulty: 15,
    scoreCompetition: 22,
    scoreMonetization: 11,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "typing-roguelike",
    title: "Keyboard Knight",
    genre: "Typing / Roguelike",
    platform: Platform.web,
    hook: "Type to attack, spell to cast spells — the roguelike that makes you faster",
    problem: "Typing games are educational/boring. Roguelikes are fun. Combine = fun learning",
    opportunity: "Typing Tutor market $200M. Browser games resurgent. Educational gaming $3B+",
    marketSize: "Educational gaming: $3B+, Browser games: resurgent",
    targetAudience: "Remote workers improving typing, students, roguelike fans",
    competitionAnalysis: "Typing of the Dead (old), ZType (basic shooter). No modern typing roguelike with depth",
    similarGames: JSON.stringify([
      { name: "Typing of the Dead", revenue: "$10M+", downloads: "1M+", notes: "Typing shooter, dated" },
      { name: "ZType", revenue: "$1M+", downloads: "Web millions", notes: "Basic typing shooter" },
      { name: "Hades", revenue: "$300M+", downloads: "10M+", notes: "Top roguelike, no typing" }
    ]),
    whyNow: "Remote work = typing matters, browser games comeback, roguelike mechanics proven",
    buildEstimateHours: 100,
    techStack: "Phaser 3 (HTML5) + Supabase + Stripe",
    monetization: "Free web version (ads) + Premium $4.99 (no ads, cloud saves) + Classroom license",
    distributionPlan: "r/mechanicalkeyboards, typing speed communities, educational blogs",
    scoreMarket: 17,
    scoreDifficulty: 21,
    scoreCompetition: 23,
    scoreMonetization: 10,
    scoreTiming: 8,
    isDraft: false,
    publishedAt: new Date(),
  },
  {
    slug: "social-deduction-dating",
    title: "Love or Lies",
    genre: "Social Deduction / Dating Sim",
    platform: Platform.mobile,
    hook: "Date 8 suitors — but 3 are AI imposters trying to break your heart",
    problem: "Dating sims are predictable. Social deduction is multiplayer. Combine = fresh solo experience",
    opportunity: "Dating sim $500M+. Social deduction viral. AI characters = infinite replayability",
    marketSize: "Dating sim: $500M+, Social deduction: $200M+",
    targetAudience: "Romance game fans, Among Us players, narrative game lovers",
    competitionAnalysis: "Dream Daddy (dating sim), Among Us (multiplayer deduction). No solo social deduction dating",
    similarGames: JSON.stringify([
      { name: "Dream Daddy", revenue: "$10M+", downloads: "2M+", notes: "Dating sim, predictable" },
      { name: "Among Us", revenue: "$500M+", downloads: "500M+", notes: "Multiplayer deduction" },
      { name: "Doki Doki Literature Club", revenue: "$10M+", downloads: "10M+", notes: "Horror dating, free" }
    ]),
    whyNow: "AI chatbot dating experiments viral, Among Us cultural impact, single-player deduction novel",
    buildEstimateHours: 140,
    techStack: "Ren'Py + GPT-4o-mini (AI suitors) + RevenueCat",
    monetization: "Premium $6.99 + Extra date scenarios DLC $2.99",
    distributionPlan: "Dating sim influencers, TikTok dating drama, r/visualnovels",
    scoreMarket: 19,
    scoreDifficulty: 18,
    scoreCompetition: 25,
    scoreMonetization: 11,
    scoreTiming: 10,
    isDraft: false,
    publishedAt: new Date(),
  },
]

async function main() {
  console.log('Seeding game ideas...')
  
  for (const idea of ideas) {
    try {
      const created = await prisma.idea.create({ data: idea })
      console.log(`✓ Created: ${created.title}`)
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`⊘ Already exists: ${idea.title}`)
      } else {
        console.error(`✗ Failed: ${idea.title}`, error.message)
      }
    }
  }
  
  console.log('Done!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
